// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////
void progress_Animation(lv_obj_t * TargetObject, int delay);


// SCREEN: ui_Screen0
void ui_Screen0_screen_init(void);
void ui_event_Screen0(lv_event_t * e);
lv_obj_t * ui_Screen0;
lv_obj_t * ui_progress;
lv_obj_t * ui_Image4;
// CUSTOM VARIABLES


// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
lv_obj_t * ui_Screen1;
lv_obj_t * ui_s1select;
lv_obj_t * ui_volumeWhite;
lv_obj_t * ui_volumeTextWhite;
lv_obj_t * ui_lightWhite;
lv_obj_t * ui_lightTextWhite;
lv_obj_t * ui_tempTextBlue;
lv_obj_t * ui_lightTextBlue;
lv_obj_t * ui_tempWhite;
lv_obj_t * ui_tempTextWhite;
lv_obj_t * ui_volumeTextBlue;
void ui_event_tempBlue(lv_event_t * e);
lv_obj_t * ui_tempBlue;
void ui_event_volumeBlue(lv_event_t * e);
lv_obj_t * ui_volumeBlue;
void ui_event_lightBlue(lv_event_t * e);
lv_obj_t * ui_lightBlue;
void ui_event_Screen1(lv_event_t * e);
int screen1_index;
// CUSTOM VARIABLES


// SCREEN: ui_Screen2
void ui_Screen2_screen_init(void);
lv_obj_t * ui_Screen2;
lv_obj_t * ui_Label4;
lv_obj_t * ui_Image3;
lv_obj_t * ui_VolNum;
lv_obj_t * ui_VolumeArc;
void ui_event_screen2ReturnBt(lv_event_t * e);
lv_obj_t * ui_screen2ReturnBt;
lv_obj_t * ui_Label3;
lv_obj_t * ui_Button1;
lv_obj_t * ui_Button2;
lv_obj_t * ui_Button3;
lv_obj_t * ui_Button4;
lv_obj_t * ui_Button5;
lv_obj_t * ui_Button6;
// CUSTOM VARIABLES


// SCREEN: ui_Screen3
void ui_Screen3_screen_init(void);
lv_obj_t * ui_Screen3;
lv_obj_t * ui_TempArc;
lv_obj_t * ui_TempNum;
lv_obj_t * ui_Image6;
lv_obj_t * ui_Label8;
void ui_event_screen3ReturnBt(lv_event_t * e);
lv_obj_t * ui_screen3ReturnBt;
lv_obj_t * ui_Label11;
lv_obj_t * ui_Button7;
lv_obj_t * ui_Button8;
lv_obj_t * ui_Button9;
lv_obj_t * ui_Button10;
lv_obj_t * ui_Button11;
lv_obj_t * ui_Button18;
// CUSTOM VARIABLES


// SCREEN: ui_Screen4
void ui_Screen4_screen_init(void);
lv_obj_t * ui_Screen4;
lv_obj_t * ui_lightArc;
lv_obj_t * ui_Image7;
lv_obj_t * ui_LightNum;
lv_obj_t * ui_Label13;
void ui_event_screen4ReturnBt(lv_event_t * e);
lv_obj_t * ui_screen4ReturnBt;
lv_obj_t * ui_Label16;
lv_obj_t * ui_Button13;
lv_obj_t * ui_Button14;
lv_obj_t * ui_Button15;
lv_obj_t * ui_Button16;
lv_obj_t * ui_Button17;
lv_obj_t * ui_Button19;
// CUSTOM VARIABLES

// EVENTS
lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS
const lv_img_dsc_t * ui_imgset_bar_bule_[1] = {&ui_img_bar_bule_02_png};
const lv_img_dsc_t * ui_imgset_bar_light_[2] = {&ui_img_bar_light_01_png, &ui_img_bar_light_02_png};
const lv_img_dsc_t * ui_imgset_bar_orange_[1] = {&ui_img_bar_orange_02_png};
const lv_img_dsc_t * ui_imgset_bar_oven_[2] = {&ui_img_bar_oven_01_png, &ui_img_bar_oven_02_png};
const lv_img_dsc_t * ui_imgset_bar_washing_[2] = {&ui_img_bar_washing_01_png, &ui_img_bar_washing_02_png};
const lv_img_dsc_t * ui_imgset_bar_yellow_[1] = {&ui_img_bar_yellow_02_png};
const lv_img_dsc_t * ui_imgset_device_control_bj_[1] = {&ui_img_device_control_bj_01_png};
const lv_img_dsc_t * ui_imgset_device_control_select_[1] = {&ui_img_device_control_select_02_png};
const lv_img_dsc_t * ui_imgset_icon_light_[2] = {&ui_img_icon_light_601_png, &ui_img_icon_light_602_png};
const lv_img_dsc_t * ui_imgset_icon_oven_settings_temp_[4] = {&ui_img_icon_oven_settings_temp_01_png, &ui_img_icon_oven_settings_temp_02_png, &ui_img_icon_oven_settings_temp_03_png, &ui_img_icon_oven_settings_temp_04_png};
const lv_img_dsc_t * ui_imgset_icon_temp_[3] = {&ui_img_icon_temp_40_png, &ui_img_icon_temp_601_png, &ui_img_icon_temp_602_png};
const lv_img_dsc_t * ui_imgset_icon_volume_[3] = {&ui_img_icon_volume_40_png, &ui_img_icon_volume_601_png, &ui_img_icon_volume_602_png};
const lv_img_dsc_t * ui_imgset_light_bj_[2] = {&ui_img_light_bj_100_png, &ui_img_light_bj_31_png};
const lv_img_dsc_t * ui_imgset_oven_bj_[1] = {&ui_img_oven_bj_01_png};
const lv_img_dsc_t * ui_imgset_power_on_light_[2] = {&ui_img_power_on_light_280_png, &ui_img_power_on_light_400_png};
const lv_img_dsc_t * ui_imgset_power_on_progress_[3] = {&ui_img_power_on_progress_01_png, &ui_img_power_on_progress_02_png, &ui_img_power_on_progress_03_png};
const lv_img_dsc_t * ui_imgset_v2_bj_light_[1] = {&ui_img_v2_bj_light_100_png};
const lv_img_dsc_t * ui_imgset_v2_bj_volume_[1] = {&ui_img_v2_bj_volume_100_png};
const lv_img_dsc_t * ui_imgset_washing_bj_[2] = {&ui_img_washing_bj_01_png, &ui_img_washing_bj_02_png};
const lv_img_dsc_t * ui_imgset_washing_bj_time_[2] = {&ui_img_washing_bj_time_100_png, &ui_img_washing_bj_time_50_png};
const lv_img_dsc_t * ui_imgset_451549298[1] = {&ui_img_911261173};
const lv_img_dsc_t * ui_imgset_power_on_light_400_[1] = {&ui_img_power_on_light_400_250707_png};

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=0
    #error "LV_COLOR_16_SWAP should be 0 to match SquareLine Studio's settings"
#endif

void anim_end_cb(lv_anim_t * anim)
{
  _ui_screen_change(&ui_Screen1, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Screen1_screen_init);
}

///////////////////// ANIMATIONS ////////////////////
void progress_Animation(lv_obj_t * TargetObject, int delay)
{
    ui_anim_user_data_t * PropertyAnimation_0_user_data = lv_mem_alloc(sizeof(ui_anim_user_data_t));
    PropertyAnimation_0_user_data->target = TargetObject;
    PropertyAnimation_0_user_data->val = -1;
    lv_anim_t PropertyAnimation_0;
    lv_anim_init(&PropertyAnimation_0);
    lv_anim_set_time(&PropertyAnimation_0, 1000);
    lv_anim_set_user_data(&PropertyAnimation_0, PropertyAnimation_0_user_data);
    lv_anim_set_custom_exec_cb(&PropertyAnimation_0, _ui_anim_callback_set_image_angle);
    lv_anim_set_values(&PropertyAnimation_0, 0, 3600);
    lv_anim_set_path_cb(&PropertyAnimation_0, lv_anim_path_linear);
    lv_anim_set_delay(&PropertyAnimation_0, delay + 0);
    lv_anim_set_deleted_cb(&PropertyAnimation_0, _ui_anim_callback_free_user_data);
    lv_anim_set_playback_time(&PropertyAnimation_0, 0);
    lv_anim_set_playback_delay(&PropertyAnimation_0, 0);
    lv_anim_set_repeat_count(&PropertyAnimation_0, 3);
    lv_anim_set_repeat_delay(&PropertyAnimation_0, 0);
    lv_anim_set_early_apply(&PropertyAnimation_0, false);
    lv_anim_set_get_value_cb(&PropertyAnimation_0, &_ui_anim_callback_get_image_angle);
    lv_anim_set_ready_cb(&PropertyAnimation_0, anim_end_cb);
    lv_anim_start(&PropertyAnimation_0);
}

///////////////////// FUNCTIONS ////////////////////
void ui_event_Screen1(lv_event_t * e)
{
  lv_event_code_t event_code = lv_event_get_code(e);
  lv_obj_t * target = lv_event_get_target(e);
  if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_LEFT) {
    lv_indev_wait_release(lv_indev_get_act());
    
    lv_obj_add_flag(ui_volumeBlue, LV_OBJ_FLAG_HIDDEN);
    lv_obj_add_flag(ui_volumeWhite, LV_OBJ_FLAG_HIDDEN);
    lv_obj_add_flag(ui_tempBlue, LV_OBJ_FLAG_HIDDEN);
    lv_obj_add_flag(ui_tempWhite, LV_OBJ_FLAG_HIDDEN);
    lv_obj_add_flag(ui_lightBlue, LV_OBJ_FLAG_HIDDEN);
    lv_obj_add_flag(ui_lightWhite, LV_OBJ_FLAG_HIDDEN);
    
    screen1_index = screen1_index - 1;
    if(screen1_index < 0)
    {
        screen1_index = 0;
    }
    switch (screen1_index) {
        case 0:  // Volume
        // volume
        lv_obj_clear_flag(ui_volumeBlue, LV_OBJ_FLAG_HIDDEN);
        lv_obj_clear_flag(ui_volumeTextBlue, LV_OBJ_FLAG_HIDDEN);
        lv_obj_add_flag(ui_volumeWhite, LV_OBJ_FLAG_HIDDEN);
        lv_obj_add_flag(ui_volumeTextWhite, LV_OBJ_FLAG_HIDDEN);
        lv_obj_set_x(ui_volumeBlue, 0);
        lv_obj_set_x(ui_volumeTextBlue, 0);
        lv_obj_set_x(ui_volumeWhite, 0);
        lv_obj_set_x(ui_volumeTextWhite, 0);

        // temp
        lv_obj_clear_flag(ui_tempWhite, LV_OBJ_FLAG_HIDDEN);
        lv_obj_clear_flag(ui_tempTextWhite, LV_OBJ_FLAG_HIDDEN);
        lv_obj_add_flag(ui_tempBlue, LV_OBJ_FLAG_HIDDEN);
        lv_obj_add_flag(ui_tempTextBlue, LV_OBJ_FLAG_HIDDEN);
        lv_obj_set_x(ui_tempBlue, 70);
        lv_obj_set_x(ui_tempTextBlue, 70);
        lv_obj_set_x(ui_tempWhite, 70);
        lv_obj_set_x(ui_tempTextWhite, 70);

        // light
        lv_obj_add_flag(ui_lightWhite, LV_OBJ_FLAG_HIDDEN);
        lv_obj_add_flag(ui_lightTextWhite, LV_OBJ_FLAG_HIDDEN);
        break;

        case 1:  // Temperature
        // volume
        lv_obj_clear_flag(ui_volumeWhite, LV_OBJ_FLAG_HIDDEN);
        lv_obj_clear_flag(ui_volumeTextWhite, LV_OBJ_FLAG_HIDDEN);
        lv_obj_add_flag(ui_volumeBlue, LV_OBJ_FLAG_HIDDEN);
        lv_obj_add_flag(ui_volumeTextBlue, LV_OBJ_FLAG_HIDDEN);
        lv_obj_set_x(ui_volumeBlue, -70);
        lv_obj_set_x(ui_volumeTextBlue, -70);
        lv_obj_set_x(ui_volumeWhite, -70);
        lv_obj_set_x(ui_volumeTextWhite, -70);

        //temp
        lv_obj_add_flag(ui_tempWhite, LV_OBJ_FLAG_HIDDEN);
        lv_obj_add_flag(ui_tempTextWhite, LV_OBJ_FLAG_HIDDEN);
        lv_obj_clear_flag(ui_tempBlue, LV_OBJ_FLAG_HIDDEN);
        lv_obj_clear_flag(ui_tempTextBlue, LV_OBJ_FLAG_HIDDEN);
        lv_obj_set_x(ui_tempBlue, 0);
        lv_obj_set_x(ui_tempTextBlue, 0);
        lv_obj_set_x(ui_tempWhite, 0);
        lv_obj_set_x(ui_tempTextWhite, 0);

        //light
        lv_obj_add_flag(ui_lightBlue, LV_OBJ_FLAG_HIDDEN);
        lv_obj_add_flag(ui_lightTextBlue, LV_OBJ_FLAG_HIDDEN);
        lv_obj_clear_flag(ui_lightWhite, LV_OBJ_FLAG_HIDDEN);
        lv_obj_clear_flag(ui_lightTextWhite, LV_OBJ_FLAG_HIDDEN);
        lv_obj_set_x(ui_lightBlue, 70);
        lv_obj_set_x(ui_lightTextBlue, 70);
        lv_obj_set_x(ui_lightWhite, 70);
        lv_obj_set_x(ui_lightTextWhite, 70);
        break;

        case 2:  // Light
        // volume
        lv_obj_add_flag(ui_volumeWhite, LV_OBJ_FLAG_HIDDEN);
        lv_obj_add_flag(ui_volumeTextWhite, LV_OBJ_FLAG_HIDDEN);
        lv_obj_add_flag(ui_volumeBlue, LV_OBJ_FLAG_HIDDEN);
        lv_obj_add_flag(ui_volumeTextBlue, LV_OBJ_FLAG_HIDDEN);

        // temp
        lv_obj_add_flag(ui_tempBlue, LV_OBJ_FLAG_HIDDEN);
        lv_obj_add_flag(ui_tempTextBlue, LV_OBJ_FLAG_HIDDEN);
        lv_obj_clear_flag(ui_tempWhite, LV_OBJ_FLAG_HIDDEN);
        lv_obj_clear_flag(ui_tempTextWhite, LV_OBJ_FLAG_HIDDEN);
        lv_obj_set_x(ui_tempBlue, -70);
        lv_obj_set_x(ui_tempTextBlue, -70);
        lv_obj_set_x(ui_tempWhite, -70);
        lv_obj_set_x(ui_tempTextWhite, -70);

        // light
        lv_obj_add_flag(ui_lightWhite, LV_OBJ_FLAG_HIDDEN);
        lv_obj_add_flag(ui_lightTextWhite, LV_OBJ_FLAG_HIDDEN);
        lv_obj_clear_flag(ui_lightBlue, LV_OBJ_FLAG_HIDDEN);
        lv_obj_clear_flag(ui_lightTextBlue, LV_OBJ_FLAG_HIDDEN);
        lv_obj_set_x(ui_lightBlue, 0);
        lv_obj_set_x(ui_lightTextBlue, 0);
        lv_obj_set_x(ui_lightWhite, 0);
        lv_obj_set_x(ui_lightTextWhite, 0);
        break;
    }
  }
  if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_RIGHT) {
    lv_indev_wait_release(lv_indev_get_act());

    lv_obj_add_flag(ui_volumeBlue, LV_OBJ_FLAG_HIDDEN);
    lv_obj_add_flag(ui_volumeWhite, LV_OBJ_FLAG_HIDDEN);
    lv_obj_add_flag(ui_tempBlue, LV_OBJ_FLAG_HIDDEN);
    lv_obj_add_flag(ui_tempWhite, LV_OBJ_FLAG_HIDDEN);
    lv_obj_add_flag(ui_lightBlue, LV_OBJ_FLAG_HIDDEN);
    lv_obj_add_flag(ui_lightWhite, LV_OBJ_FLAG_HIDDEN);
    screen1_index = screen1_index + 1;
    if(screen1_index > 2)
    {
        screen1_index = 2;
    }
    switch (screen1_index) {
        case 0:  // Volume
        // volume
        lv_obj_clear_flag(ui_volumeBlue, LV_OBJ_FLAG_HIDDEN);
        lv_obj_clear_flag(ui_volumeTextBlue, LV_OBJ_FLAG_HIDDEN);
        lv_obj_add_flag(ui_volumeWhite, LV_OBJ_FLAG_HIDDEN);
        lv_obj_add_flag(ui_volumeTextWhite, LV_OBJ_FLAG_HIDDEN);
        lv_obj_set_x(ui_volumeBlue, 0);
        lv_obj_set_x(ui_volumeTextBlue, 0);
        lv_obj_set_x(ui_volumeWhite, 0);
        lv_obj_set_x(ui_volumeTextWhite, 0);

        // temp
        lv_obj_clear_flag(ui_tempWhite, LV_OBJ_FLAG_HIDDEN);
        lv_obj_clear_flag(ui_tempTextWhite, LV_OBJ_FLAG_HIDDEN);
        lv_obj_add_flag(ui_tempBlue, LV_OBJ_FLAG_HIDDEN);
        lv_obj_add_flag(ui_tempTextBlue, LV_OBJ_FLAG_HIDDEN);
        lv_obj_set_x(ui_tempBlue, 70);
        lv_obj_set_x(ui_tempTextBlue, 70);
        lv_obj_set_x(ui_tempWhite, 70);
        lv_obj_set_x(ui_tempTextWhite, 70);

        // light
        lv_obj_add_flag(ui_lightWhite, LV_OBJ_FLAG_HIDDEN);
        lv_obj_add_flag(ui_lightTextWhite, LV_OBJ_FLAG_HIDDEN);
        break;

        case 1:  // Temperature
        // volume
        lv_obj_clear_flag(ui_volumeWhite, LV_OBJ_FLAG_HIDDEN);
        lv_obj_clear_flag(ui_volumeTextWhite, LV_OBJ_FLAG_HIDDEN);
        lv_obj_add_flag(ui_volumeBlue, LV_OBJ_FLAG_HIDDEN);
        lv_obj_add_flag(ui_volumeTextBlue, LV_OBJ_FLAG_HIDDEN);
        lv_obj_set_x(ui_volumeBlue, -70);
        lv_obj_set_x(ui_volumeTextBlue, -70);
        lv_obj_set_x(ui_volumeWhite, -70);
        lv_obj_set_x(ui_volumeTextWhite, -70);

        //temp
        lv_obj_add_flag(ui_tempWhite, LV_OBJ_FLAG_HIDDEN);
        lv_obj_add_flag(ui_tempTextWhite, LV_OBJ_FLAG_HIDDEN);
        lv_obj_clear_flag(ui_tempBlue, LV_OBJ_FLAG_HIDDEN);
        lv_obj_clear_flag(ui_tempTextBlue, LV_OBJ_FLAG_HIDDEN);
        lv_obj_set_x(ui_tempBlue, 0);
        lv_obj_set_x(ui_tempTextBlue, 0);
        lv_obj_set_x(ui_tempWhite, 0);
        lv_obj_set_x(ui_tempTextWhite, 0);

        //light
        lv_obj_add_flag(ui_lightBlue, LV_OBJ_FLAG_HIDDEN);
        lv_obj_add_flag(ui_lightTextBlue, LV_OBJ_FLAG_HIDDEN);
        lv_obj_clear_flag(ui_lightWhite, LV_OBJ_FLAG_HIDDEN);
        lv_obj_clear_flag(ui_lightTextWhite, LV_OBJ_FLAG_HIDDEN);
        lv_obj_set_x(ui_lightBlue, 70);
        lv_obj_set_x(ui_lightTextBlue, 70);
        lv_obj_set_x(ui_lightWhite, 70);
        lv_obj_set_x(ui_lightTextWhite, 70);
        break;

        case 2:  // Light
        // volume
        lv_obj_add_flag(ui_volumeWhite, LV_OBJ_FLAG_HIDDEN);
        lv_obj_add_flag(ui_volumeTextWhite, LV_OBJ_FLAG_HIDDEN);
        lv_obj_add_flag(ui_volumeBlue, LV_OBJ_FLAG_HIDDEN);
        lv_obj_add_flag(ui_volumeTextBlue, LV_OBJ_FLAG_HIDDEN);

        // temp
        lv_obj_add_flag(ui_tempBlue, LV_OBJ_FLAG_HIDDEN);
        lv_obj_add_flag(ui_tempTextBlue, LV_OBJ_FLAG_HIDDEN);
        lv_obj_clear_flag(ui_tempWhite, LV_OBJ_FLAG_HIDDEN);
        lv_obj_clear_flag(ui_tempTextWhite, LV_OBJ_FLAG_HIDDEN);
        lv_obj_set_x(ui_tempBlue, -70);
        lv_obj_set_x(ui_tempTextBlue, -70);
        lv_obj_set_x(ui_tempWhite, -70);
        lv_obj_set_x(ui_tempTextWhite, -70);

        // light
        lv_obj_add_flag(ui_lightWhite, LV_OBJ_FLAG_HIDDEN);
        lv_obj_add_flag(ui_lightTextWhite, LV_OBJ_FLAG_HIDDEN);
        lv_obj_clear_flag(ui_lightBlue, LV_OBJ_FLAG_HIDDEN);
        lv_obj_clear_flag(ui_lightTextBlue, LV_OBJ_FLAG_HIDDEN);
        lv_obj_set_x(ui_lightBlue, 0);
        lv_obj_set_x(ui_lightTextBlue, 0);
        lv_obj_set_x(ui_lightWhite, 0);
        lv_obj_set_x(ui_lightTextWhite, 0);
        break;
    }
  }
}

void ui_event_Screen0(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_SCREEN_LOADED) {
        progress_Animation(ui_progress, 0);
    }
}

// void ui_event_tempBlue(lv_event_t * e)
// {
//     lv_event_code_t event_code = lv_event_get_code(e);

//     if(event_code == LV_EVENT_CLICKED) {
//         _ui_screen_change(&ui_Screen3, LV_SCR_LOAD_ANIM_FADE_ON, 200, 0, &ui_Screen3_screen_init);
//     }
// }

// void ui_event_volumeBlue(lv_event_t * e)
// {
//     lv_event_code_t event_code = lv_event_get_code(e);

//     if(event_code == LV_EVENT_CLICKED) {
//         _ui_screen_change(&ui_Screen2, LV_SCR_LOAD_ANIM_FADE_ON, 200, 0, &ui_Screen2_screen_init);
//     }
// }

// void ui_event_lightBlue(lv_event_t * e)
// {
//     lv_event_code_t event_code = lv_event_get_code(e);

//     if(event_code == LV_EVENT_CLICKED) {
//         _ui_screen_change(&ui_Screen4, LV_SCR_LOAD_ANIM_FADE_ON, 200, 0, &ui_Screen4_screen_init);
//     }
// }

// void ui_event_screen2ReturnBt(lv_event_t * e)
// {
//     lv_event_code_t event_code = lv_event_get_code(e);

//     if(event_code == LV_EVENT_CLICKED) {
//         _ui_screen_change(&ui_Screen1, LV_SCR_LOAD_ANIM_FADE_ON, 200, 0, &ui_Screen1_screen_init);
//     }
// }

// void ui_event_screen3ReturnBt(lv_event_t * e)
// {
//     lv_event_code_t event_code = lv_event_get_code(e);

//     if(event_code == LV_EVENT_CLICKED) {
//         _ui_screen_change(&ui_Screen1, LV_SCR_LOAD_ANIM_FADE_ON, 200, 0, &ui_Screen1_screen_init);
//     }
// }

// void ui_event_screen4RerutnBt(lv_event_t * e)
// {
//     lv_event_code_t event_code = lv_event_get_code(e);

//     if(event_code == LV_EVENT_CLICKED) {
//         _ui_screen_change(&ui_Screen1, LV_SCR_LOAD_ANIM_FADE_ON, 200, 0, &ui_Screen1_screen_init);
//     }
// }

void ui_event_volumeBlue(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_RELEASED) {
        lv_obj_t * current_screen = lv_scr_act();
        if (current_screen == ui_Screen1) {
            _ui_screen_change(&ui_Screen2, LV_SCR_LOAD_ANIM_FADE_ON, 200, 0, &ui_Screen2_screen_init);
        }
    }
}

void ui_event_tempBlue(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_RELEASED) {
        lv_obj_t * current_screen = lv_scr_act();
        if (current_screen == ui_Screen1) {
             _ui_screen_change(&ui_Screen3, LV_SCR_LOAD_ANIM_FADE_ON, 200, 0, &ui_Screen3_screen_init);
        }
    }
}

void ui_event_lightBlue(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_RELEASED) {
        lv_obj_t * current_screen = lv_scr_act();
        if (current_screen == ui_Screen1) {
            _ui_screen_change(&ui_Screen4, LV_SCR_LOAD_ANIM_FADE_ON, 200, 0, &ui_Screen4_screen_init);
        }
    }
}

void ui_event_screen2ReturnBt(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_RELEASED) {
        _ui_screen_change(&ui_Screen1, LV_SCR_LOAD_ANIM_FADE_ON, 200, 0, &ui_Screen1_screen_init);
    }
}

void ui_event_screen3ReturnBt(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_RELEASED) {
        _ui_screen_change(&ui_Screen1, LV_SCR_LOAD_ANIM_FADE_ON, 200, 0, &ui_Screen1_screen_init);
    }
}

void ui_event_screen4ReturnBt(lv_event_t * e)  
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_RELEASED) {
        _ui_screen_change(&ui_Screen1, LV_SCR_LOAD_ANIM_FADE_ON, 200, 0, &ui_Screen1_screen_init);
    }
}

///////////////////// SCREENS ////////////////////

void ui_init(void)
{
    LV_EVENT_GET_COMP_CHILD = lv_event_register_id();

    lv_disp_t * dispp = lv_disp_get_default();
    lv_theme_t * theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED),
                                               false, LV_FONT_DEFAULT);
    lv_disp_set_theme(dispp, theme);
    ui_Screen0_screen_init();
    ui_Screen1_screen_init();
    ui_Screen2_screen_init();
    ui_Screen3_screen_init();
    ui_Screen4_screen_init();
    ui____initial_actions0 = lv_obj_create(NULL);
    lv_disp_load_scr(ui_Screen0);
}
