// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#ifndef _SQUARELINE_PROJECT_UI_H
#define _SQUARELINE_PROJECT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

#include "ui_helpers.h"
#include "ui_comp.h"
#include "ui_comp_hook.h"
#include "ui_events.h"

void progress_Animation(lv_obj_t * TargetObject, int delay);

// SCREEN: ui_Screen0
void ui_Screen0_screen_init(void);
void ui_event_Screen0(lv_event_t * e);
extern lv_obj_t * ui_Screen0;
extern lv_obj_t * ui_progress;
extern lv_obj_t * ui_Image4;
// CUSTOM VARIABLES

// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
extern lv_obj_t * ui_Screen1;
extern lv_obj_t * ui_s1select;
extern lv_obj_t * ui_volumeWhite;
extern lv_obj_t * ui_volumeTextWhite;
extern lv_obj_t * ui_lightWhite;
extern lv_obj_t * ui_lightTextWhite;
extern lv_obj_t * ui_tempTextBlue;
extern lv_obj_t * ui_lightTextBlue;
extern lv_obj_t * ui_tempWhite;
extern lv_obj_t * ui_tempTextWhite;
extern lv_obj_t * ui_volumeTextBlue;
void ui_event_tempBlue(lv_event_t * e);
extern lv_obj_t * ui_tempBlue;
void ui_event_volumeBlue(lv_event_t * e);
extern lv_obj_t * ui_volumeBlue;
void ui_event_lightBlue(lv_event_t * e);
extern lv_obj_t * ui_lightBlue;
extern int screen1_index;
void ui_event_Screen1(lv_event_t * e);
// CUSTOM VARIABLES

// SCREEN: ui_Screen2
void ui_Screen2_screen_init(void);
extern lv_obj_t * ui_Screen2;
extern lv_obj_t * ui_Label4;
extern lv_obj_t * ui_Image3;
extern lv_obj_t * ui_VolNum;
extern lv_obj_t * ui_VolumeArc;
void ui_event_screen2ReturnBt(lv_event_t * e);
extern lv_obj_t * ui_screen2ReturnBt;
extern lv_obj_t * ui_Label3;
extern lv_obj_t * ui_Button1;
extern lv_obj_t * ui_Button2;
extern lv_obj_t * ui_Button3;
extern lv_obj_t * ui_Button4;
extern lv_obj_t * ui_Button5;
extern lv_obj_t * ui_Button6;
// CUSTOM VARIABLES

// SCREEN: ui_Screen3
void ui_Screen3_screen_init(void);
extern lv_obj_t * ui_Screen3;
extern lv_obj_t * ui_TempArc;
extern lv_obj_t * ui_TempNum;
extern lv_obj_t * ui_Image6;
extern lv_obj_t * ui_Label8;
void ui_event_screen3ReturnBt(lv_event_t * e);
extern lv_obj_t * ui_screen3ReturnBt;
extern lv_obj_t * ui_Label11;
extern lv_obj_t * ui_Button7;
extern lv_obj_t * ui_Button8;
extern lv_obj_t * ui_Button9;
extern lv_obj_t * ui_Button10;
extern lv_obj_t * ui_Button11;
extern lv_obj_t * ui_Button18;
// CUSTOM VARIABLES

// SCREEN: ui_Screen4
void ui_Screen4_screen_init(void);
extern lv_obj_t * ui_Screen4;
extern lv_obj_t * ui_lightArc;
extern lv_obj_t * ui_Image7;
extern lv_obj_t * ui_LightNum;
extern lv_obj_t * ui_Label13;
void ui_event_screen4ReturnBt(lv_event_t * e);
extern lv_obj_t * ui_screen4ReturnBt;
extern lv_obj_t * ui_Label16;
extern lv_obj_t * ui_Button13;
extern lv_obj_t * ui_Button14;
extern lv_obj_t * ui_Button15;
extern lv_obj_t * ui_Button16;
extern lv_obj_t * ui_Button17;
extern lv_obj_t * ui_Button19;
// CUSTOM VARIABLES

// EVENTS

extern lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE(ui_img_power_on_progress_60px_png);    // assets/power_on_progress_60px.png
LV_IMG_DECLARE(ui_img_power_on_light_400_250707_png);    // assets/power_on_light_400_250707.png
LV_IMG_DECLARE(ui_img_device_control_bj_01_png);    // assets/device_control_bj_01.png
LV_IMG_DECLARE(ui_img_device_control_select_02_png);    // assets/device_control_select_02.png
LV_IMG_DECLARE(ui_img_icon_volume_601_png);    // assets/icon_volume_601.png
LV_IMG_DECLARE(ui_img_icon_light_601_png);    // assets/icon_light_601.png
LV_IMG_DECLARE(ui_img_icon_temp_601_png);    // assets/icon_temp_601.png
LV_IMG_DECLARE(ui_img_icon_temp_602_png);    // assets/icon_temp_602.png
LV_IMG_DECLARE(ui_img_icon_volume_602_png);    // assets/icon_volume_602.png
LV_IMG_DECLARE(ui_img_icon_light_602_png);    // assets/icon_light_602.png
LV_IMG_DECLARE(ui_img_v2_bj_volume_100_png);    // assets/v2_bj_volume_100.png
LV_IMG_DECLARE(ui_img_icon_volume_40_png);    // assets/icon_volume_40.png
LV_IMG_DECLARE(ui_img_bar_light_01_png);    // assets/bar_light_01.png
LV_IMG_DECLARE(ui_img_bar_bule_02_png);    // assets/bar_bule_02.png
LV_IMG_DECLARE(ui_img_v2_bj_temp_png);    // assets/v2_bj_temp.png
LV_IMG_DECLARE(ui_img_bar_oven_01_png);    // assets/bar_oven_01.png
LV_IMG_DECLARE(ui_img_bar_orange_02_png);    // assets/bar_orange_02.png
LV_IMG_DECLARE(ui_img_icon_temp_40_png);    // assets/icon_temp_40.png
LV_IMG_DECLARE(ui_img_v2_bj_light_100_png);    // assets/v2_bj_light_100.png
LV_IMG_DECLARE(ui_img_bar_white_png);    // assets/bar_white.png
LV_IMG_DECLARE(ui_img_bar_yellow_02_png);    // assets/bar_yellow_02.png
LV_IMG_DECLARE(ui_img_750753901);    // assets/icon_light_601(1).png
LV_IMG_DECLARE(ui_img_bar_light_02_png);    // assets/bar_light_02.png
LV_IMG_DECLARE(ui_img_bar_oven_02_png);    // assets/bar_oven_02.png
LV_IMG_DECLARE(ui_img_bar_washing_01_png);    // assets/bar_washing_01.png
LV_IMG_DECLARE(ui_img_bar_washing_02_png);    // assets/bar_washing_02.png
LV_IMG_DECLARE(ui_img_icon_oven_settings_temp_01_png);    // assets/icon_oven_settings_temp_01.png
LV_IMG_DECLARE(ui_img_icon_oven_settings_temp_02_png);    // assets/icon_oven_settings_temp_02.png
LV_IMG_DECLARE(ui_img_icon_oven_settings_temp_03_png);    // assets/icon_oven_settings_temp_03.png
LV_IMG_DECLARE(ui_img_icon_oven_settings_temp_04_png);    // assets/icon_oven_settings_temp_04.png
LV_IMG_DECLARE(ui_img_light_bj_100_png);    // assets/light_bj_100.png
LV_IMG_DECLARE(ui_img_light_bj_31_png);    // assets/light_bj_31.png
LV_IMG_DECLARE(ui_img_oven_bj_01_png);    // assets/oven_bj_01.png
LV_IMG_DECLARE(ui_img_power_on_light_280_png);    // assets/power_on_light_280.png
LV_IMG_DECLARE(ui_img_power_on_light_400_png);    // assets/power_on_light_400.png
LV_IMG_DECLARE(ui_img_power_on_progress_01_png);    // assets/power_on_progress_01.png
LV_IMG_DECLARE(ui_img_power_on_progress_02_png);    // assets/power_on_progress_02.png
LV_IMG_DECLARE(ui_img_power_on_progress_03_png);    // assets/power_on_progress_03.png
LV_IMG_DECLARE(ui_img_washing_bj_01_png);    // assets/washing_bj_01.png
LV_IMG_DECLARE(ui_img_washing_bj_02_png);    // assets/washing_bj_02.png
LV_IMG_DECLARE(ui_img_washing_bj_time_100_png);    // assets/washing_bj_time_100.png
LV_IMG_DECLARE(ui_img_washing_bj_time_50_png);    // assets/washing_bj_time_50.png
LV_IMG_DECLARE(ui_img_911261173);    // assets/椭圆 1 拷贝 2.png

// UI INIT
void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
