// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#ifndef _UI_COMP_CPN_IMG0RB0_H
#define _UI_COMP_CPN_IMG0RB0_H

#include "ui.h"

#ifdef __cplusplus
extern "C" {
#endif

// COMPONENT cpn_img0rb0
#define UI_COMP_CPN_IMG0RB0_CPN_IMG0RB0 0
#define _UI_COMP_CPN_IMG0RB0_NUM 1
lv_obj_t * ui_cpn_img0rb0_create(lv_obj_t * comp_parent);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
