// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "ui.h"


// COMPONENT cpn_img0rb0

lv_obj_t * ui_cpn_img0rb0_create(lv_obj_t * comp_parent)
{

    lv_obj_t * cui_cpn_img0rb0;
    cui_cpn_img0rb0 = lv_img_create(comp_parent);
    lv_obj_set_height(cui_cpn_img0rb0, 200);
    lv_obj_set_width(cui_cpn_img0rb0, lv_pct(100));
    lv_obj_set_align(cui_cpn_img0rb0, LV_ALIGN_CENTER);
    lv_obj_add_flag(cui_cpn_img0rb0, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(cui_cpn_img0rb0, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_t ** children = lv_mem_alloc(sizeof(lv_obj_t *) * _UI_COMP_CPN_IMG0RB0_NUM);
    children[UI_COMP_CPN_IMG0RB0_CPN_IMG0RB0] = cui_cpn_img0rb0;
    lv_obj_add_event_cb(cui_cpn_img0rb0, get_component_child_event_cb, LV_EVENT_GET_COMP_CHILD, children);
    lv_obj_add_event_cb(cui_cpn_img0rb0, del_component_child_event_cb, LV_EVENT_DELETE, children);
    ui_comp_cpn_img0rb0_create_hook(cui_cpn_img0rb0);
    return cui_cpn_img0rb0;
}

