// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "ui.h"

void s2_arc_event_cb(lv_event_t *e) {
  lv_event_code_t code = lv_event_get_code(e);
  lv_obj_t *arc = lv_event_get_target(e);

  if (code == LV_EVENT_VALUE_CHANGED) {
    int value = lv_arc_get_value(arc);
    char volText[8];
    if (value == 100) {
      snprintf(volText, sizeof(volText), "%d%%", value);
      lv_label_set_text(ui_VolNum, volText);
    } else {
      snprintf(volText, sizeof(volText), " %d%%", value);
      lv_label_set_text(ui_VolNum, volText);
    }
  } 
}

void ui_Screen2_screen_init(void)
{
    ui_Screen2 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Screen2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Screen2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_Screen2, &ui_img_v2_bj_volume_100_png, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label4 = lv_label_create(ui_Screen2);
    lv_obj_set_width(ui_Label4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label4, 0);
    lv_obj_set_y(ui_Label4, 35);
    lv_obj_set_align(ui_Label4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label4, "Volume");
    lv_obj_set_style_text_color(ui_Label4, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image3 = lv_img_create(ui_Screen2);
    lv_img_set_src(ui_Image3, &ui_img_icon_volume_40_png);
    lv_obj_set_width(ui_Image3, 20);
    lv_obj_set_height(ui_Image3, 20);
    lv_obj_set_x(ui_Image3, 0);
    lv_obj_set_y(ui_Image3, -48);
    lv_obj_set_align(ui_Image3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image3, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_VolNum = lv_label_create(ui_Screen2);
    lv_obj_set_width(ui_VolNum, 114);
    lv_obj_set_height(ui_VolNum, 56);
    lv_obj_set_x(ui_VolNum, 4);
    lv_obj_set_y(ui_VolNum, 3);
    lv_obj_set_align(ui_VolNum, LV_ALIGN_CENTER);
    lv_label_set_text(ui_VolNum, " 50%");
    lv_obj_set_style_text_color(ui_VolNum, lv_color_hex(0x33DCFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_VolNum, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_VolNum, &lv_font_montserrat_40, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_VolumeArc = lv_arc_create(ui_Screen2);
    lv_obj_set_width(ui_VolumeArc, 176);
    lv_obj_set_height(ui_VolumeArc, 181);
    lv_obj_set_x(ui_VolumeArc, -1);
    lv_obj_set_y(ui_VolumeArc, 4);
    lv_obj_set_align(ui_VolumeArc, LV_ALIGN_CENTER);
    lv_arc_set_value(ui_VolumeArc, 50);
    lv_obj_set_style_arc_width(ui_VolumeArc, 25, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_rounded(ui_VolumeArc, false, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_img_src(ui_VolumeArc, &ui_img_bar_light_01_png, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_arc_width(ui_VolumeArc, 25, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_rounded(ui_VolumeArc, false, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_img_src(ui_VolumeArc, &ui_img_bar_bule_02_png, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_VolumeArc, lv_color_hex(0x000000), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_VolumeArc, 0, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_VolumeArc, 0, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_VolumeArc, 255, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_screen2ReturnBt = lv_btn_create(ui_Screen2);
    lv_obj_set_width(ui_screen2ReturnBt, 60);
    lv_obj_set_height(ui_screen2ReturnBt, 24);
    lv_obj_set_x(ui_screen2ReturnBt, 0);
    lv_obj_set_y(ui_screen2ReturnBt, 72);
    lv_obj_set_align(ui_screen2ReturnBt, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_screen2ReturnBt, lv_color_hex(0x33DCFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_screen2ReturnBt, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_screen2ReturnBt, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_screen2ReturnBt, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label3 = lv_label_create(ui_Screen2);
    lv_obj_set_width(ui_Label3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label3, 0);
    lv_obj_set_y(ui_Label3, 71);
    lv_obj_set_align(ui_Label3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label3, "Return");
    lv_obj_set_style_text_font(ui_Label3, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button1 = lv_btn_create(ui_Screen2);
    lv_obj_set_width(ui_Button1, 27);
    lv_obj_set_height(ui_Button1, 152);
    lv_obj_set_x(ui_Button1, -44);
    lv_obj_set_y(ui_Button1, 27);
    lv_obj_set_align(ui_Button1, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_Button1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_Button1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_Button1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button2 = lv_btn_create(ui_Screen2);
    lv_obj_set_width(ui_Button2, 26);
    lv_obj_set_height(ui_Button2, 147);
    lv_obj_set_x(ui_Button2, 41);
    lv_obj_set_y(ui_Button2, 27);
    lv_obj_set_align(ui_Button2, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_Button2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_Button2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_Button2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button3 = lv_btn_create(ui_Screen2);
    lv_obj_set_width(ui_Button3, 72);
    lv_obj_set_height(ui_Button3, 27);
    lv_obj_set_x(ui_Button3, 2);
    lv_obj_set_y(ui_Button3, 97);
    lv_obj_set_align(ui_Button3, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_Button3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_Button3, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_Button3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button4 = lv_btn_create(ui_Screen2);
    lv_obj_set_width(ui_Button4, 57);
    lv_obj_set_height(ui_Button4, 50);
    lv_obj_set_x(ui_Button4, -2);
    lv_obj_set_y(ui_Button4, 33);
    lv_obj_set_align(ui_Button4, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_Button4, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_Button4, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_Button4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button5 = lv_btn_create(ui_Screen2);
    lv_obj_set_width(ui_Button5, 72);
    lv_obj_set_height(ui_Button5, 36);
    lv_obj_set_x(ui_Button5, -66);
    lv_obj_set_y(ui_Button5, 78);
    lv_obj_set_align(ui_Button5, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_Button5, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button5, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_Button5, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_Button5, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button6 = lv_btn_create(ui_Screen2);
    lv_obj_set_width(ui_Button6, 66);
    lv_obj_set_height(ui_Button6, 33);
    lv_obj_set_x(ui_Button6, 64);
    lv_obj_set_y(ui_Button6, 75);
    lv_obj_set_align(ui_Button6, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_Button6, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button6, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_Button6, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_Button6, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_screen2ReturnBt, ui_event_screen2ReturnBt, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_VolumeArc, s2_arc_event_cb, LV_EVENT_ALL, NULL);

}
