// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "ui.h"

void ui_Screen1_screen_init(void)
{
    ui_Screen1 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Screen1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Screen1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_Screen1, &ui_img_device_control_bj_01_png, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_s1select = lv_img_create(ui_Screen1);
    lv_img_set_src(ui_s1select, &ui_img_device_control_select_02_png);
    lv_obj_set_width(ui_s1select, LV_SIZE_CONTENT);   /// 70
    lv_obj_set_height(ui_s1select, LV_SIZE_CONTENT);    /// 200
    lv_obj_set_align(ui_s1select, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_s1select, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_s1select, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_volumeWhite = lv_img_create(ui_Screen1);
    lv_img_set_src(ui_volumeWhite, &ui_img_icon_volume_601_png);
    lv_obj_set_width(ui_volumeWhite, LV_SIZE_CONTENT);   /// 36
    lv_obj_set_height(ui_volumeWhite, LV_SIZE_CONTENT);    /// 40
    lv_obj_set_x(ui_volumeWhite, -70);
    lv_obj_set_y(ui_volumeWhite, -9);
    lv_obj_set_align(ui_volumeWhite, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_volumeWhite, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_volumeWhite, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_volumeTextWhite = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_volumeTextWhite, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_volumeTextWhite, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_volumeTextWhite, -69);
    lv_obj_set_y(ui_volumeTextWhite, 21);
    lv_obj_set_align(ui_volumeTextWhite, LV_ALIGN_CENTER);
    lv_label_set_text(ui_volumeTextWhite, "Volume");
    lv_obj_set_style_text_color(ui_volumeTextWhite, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_volumeTextWhite, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_volumeTextWhite, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_volumeTextWhite, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lightWhite = lv_img_create(ui_Screen1);
    lv_img_set_src(ui_lightWhite, &ui_img_icon_light_601_png);
    lv_obj_set_width(ui_lightWhite, LV_SIZE_CONTENT);   /// 36
    lv_obj_set_height(ui_lightWhite, LV_SIZE_CONTENT);    /// 40
    lv_obj_set_x(ui_lightWhite, 70);
    lv_obj_set_y(ui_lightWhite, -9);
    lv_obj_set_align(ui_lightWhite, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_lightWhite, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_lightWhite, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_lightTextWhite = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_lightTextWhite, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lightTextWhite, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lightTextWhite, 70);
    lv_obj_set_y(ui_lightTextWhite, 20);
    lv_obj_set_align(ui_lightTextWhite, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lightTextWhite, "Light");
    lv_obj_set_style_text_color(ui_lightTextWhite, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lightTextWhite, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_lightTextWhite, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lightTextWhite, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_tempTextBlue = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_tempTextBlue, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_tempTextBlue, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_tempTextBlue, 0);
    lv_obj_set_y(ui_tempTextBlue, 21);
    lv_obj_set_align(ui_tempTextBlue, LV_ALIGN_CENTER);
    lv_label_set_text(ui_tempTextBlue, "Temp");
    lv_obj_set_style_text_color(ui_tempTextBlue, lv_color_hex(0x00FFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_tempTextBlue, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_tempTextBlue, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_tempTextBlue, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lightTextBlue = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_lightTextBlue, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lightTextBlue, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lightTextBlue, 70);
    lv_obj_set_y(ui_lightTextBlue, 20);
    lv_obj_set_align(ui_lightTextBlue, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lightTextBlue, "Light");
    lv_obj_add_flag(ui_lightTextBlue, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_set_style_text_color(ui_lightTextBlue, lv_color_hex(0x00FFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lightTextBlue, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lightTextBlue, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_tempWhite = lv_img_create(ui_Screen1);
    lv_img_set_src(ui_tempWhite, &ui_img_icon_temp_601_png);
    lv_obj_set_width(ui_tempWhite, LV_SIZE_CONTENT);   /// 36
    lv_obj_set_height(ui_tempWhite, LV_SIZE_CONTENT);    /// 40
    lv_obj_set_x(ui_tempWhite, 0);
    lv_obj_set_y(ui_tempWhite, -9);
    lv_obj_set_align(ui_tempWhite, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_tempWhite, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_tempWhite, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_tempTextWhite = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_tempTextWhite, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_tempTextWhite, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_tempTextWhite, 0);
    lv_obj_set_y(ui_tempTextWhite, 21);
    lv_obj_set_align(ui_tempTextWhite, LV_ALIGN_CENTER);
    lv_label_set_text(ui_tempTextWhite, "Temp");
    lv_obj_add_flag(ui_tempTextWhite, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_set_style_text_color(ui_tempTextWhite, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_tempTextWhite, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_tempTextWhite, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_volumeTextBlue = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_volumeTextBlue, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_volumeTextBlue, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_volumeTextBlue, -69);
    lv_obj_set_y(ui_volumeTextBlue, 21);
    lv_obj_set_align(ui_volumeTextBlue, LV_ALIGN_CENTER);
    lv_label_set_text(ui_volumeTextBlue, "Volume");
    lv_obj_add_flag(ui_volumeTextBlue, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_set_style_text_color(ui_volumeTextBlue, lv_color_hex(0x00FFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_volumeTextBlue, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_volumeTextBlue, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_tempBlue = lv_btn_create(ui_Screen1);
    lv_obj_set_width(ui_tempBlue, 40);
    lv_obj_set_height(ui_tempBlue, 40);
    lv_obj_set_x(ui_tempBlue, 0);
    lv_obj_set_y(ui_tempBlue, -9);
    lv_obj_set_align(ui_tempBlue, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_tempBlue, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_tempBlue, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_tempBlue, &ui_img_icon_temp_602_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_tempBlue, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_tempBlue, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_volumeBlue = lv_btn_create(ui_Screen1);
    lv_obj_set_width(ui_volumeBlue, 40);
    lv_obj_set_height(ui_volumeBlue, 40);
    lv_obj_set_x(ui_volumeBlue, -70);
    lv_obj_set_y(ui_volumeBlue, -9);
    lv_obj_set_align(ui_volumeBlue, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_volumeBlue, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_set_style_bg_color(ui_volumeBlue, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_volumeBlue, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_volumeBlue, &ui_img_icon_volume_602_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_volumeBlue, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_volumeBlue, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lightBlue = lv_btn_create(ui_Screen1);
    lv_obj_set_width(ui_lightBlue, 30);
    lv_obj_set_height(ui_lightBlue, 30);
    lv_obj_set_x(ui_lightBlue, 70);
    lv_obj_set_y(ui_lightBlue, -9);
    lv_obj_set_align(ui_lightBlue, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_lightBlue, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_set_style_bg_color(ui_lightBlue, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_lightBlue, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_lightBlue, &ui_img_icon_light_602_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_lightBlue, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_lightBlue, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_tempBlue, ui_event_tempBlue, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_volumeBlue, ui_event_volumeBlue, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_lightBlue, ui_event_lightBlue, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Screen1, ui_event_Screen1, LV_EVENT_ALL, NULL);

}
