// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "ui.h"

#define SCREEN_BACKLIGHT_PIN 46
const int pwmFreq = 5000;
const int pwmChannel = 0;
const int pwmResolution = 8;

void s4_arc_event_cb(lv_event_t *e) {
  lv_event_code_t code = lv_event_get_code(e);
  lv_obj_t *arc = lv_event_get_target(e);

  if (code == LV_EVENT_VALUE_CHANGED) {
    int value = lv_arc_get_value(arc);
    
    int pwm_value = (value * 255) / 100;
    ledcSetup(pwmChannel, pwmFreq, pwmResolution);
    ledcAttachPin(SCREEN_BACKLIGHT_PIN, pwmChannel);
    ledcWrite(pwmChannel, pwm_value);

    char lightText[8];
    if (value == 100) {
      snprintf(lightText, sizeof(lightText), "%d%%", value);
      lv_label_set_text(ui_LightNum, lightText);
    } else {
      snprintf(lightText, sizeof(lightText), " %d%%", value);
      lv_label_set_text(ui_LightNum, lightText);
    }
  } 
}

void ui_Screen4_screen_init(void)
{
    ui_Screen4 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Screen4, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Screen4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_Screen4, &ui_img_v2_bj_light_100_png, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lightArc = lv_arc_create(ui_Screen4);
    lv_obj_set_width(ui_lightArc, 176);
    lv_obj_set_height(ui_lightArc, 181);
    lv_obj_set_align(ui_lightArc, LV_ALIGN_CENTER);
    lv_arc_set_value(ui_lightArc, 50);
    lv_obj_set_style_arc_img_src(ui_lightArc, &ui_img_bar_white_png, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_arc_rounded(ui_lightArc, false, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_img_src(ui_lightArc, &ui_img_bar_yellow_02_png, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_lightArc, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_lightArc, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_Image7 = lv_img_create(ui_Screen4);
    lv_img_set_src(ui_Image7, &ui_img_750753901);
    lv_obj_set_width(ui_Image7, LV_SIZE_CONTENT);   /// 20
    lv_obj_set_height(ui_Image7, LV_SIZE_CONTENT);    /// 20
    lv_obj_set_x(ui_Image7, 1);
    lv_obj_set_y(ui_Image7, -45);
    lv_obj_set_align(ui_Image7, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image7, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image7, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_LightNum = lv_label_create(ui_Screen4);
    lv_obj_set_width(ui_LightNum, 114);
    lv_obj_set_height(ui_LightNum, 56);
    lv_obj_set_x(ui_LightNum, 4);
    lv_obj_set_y(ui_LightNum, 3);
    lv_obj_set_align(ui_LightNum, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LightNum, " 50%");
    lv_obj_set_style_text_color(ui_LightNum, lv_color_hex(0xFFD400), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LightNum, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LightNum, &lv_font_montserrat_40, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label13 = lv_label_create(ui_Screen4);
    lv_obj_set_width(ui_Label13, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label13, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label13, 0);
    lv_obj_set_y(ui_Label13, 34);
    lv_obj_set_align(ui_Label13, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label13, "Light");
    lv_obj_set_style_text_color(ui_Label13, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label13, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_screen4ReturnBt = lv_btn_create(ui_Screen4);
    lv_obj_set_width(ui_screen4ReturnBt, 60);
    lv_obj_set_height(ui_screen4ReturnBt, 24);
    lv_obj_set_x(ui_screen4ReturnBt, 0);
    lv_obj_set_y(ui_screen4ReturnBt, 72);
    lv_obj_set_align(ui_screen4ReturnBt, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_screen4ReturnBt, lv_color_hex(0x33DCFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_screen4ReturnBt, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_screen4ReturnBt, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_screen4ReturnBt, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label16 = lv_label_create(ui_Screen4);
    lv_obj_set_width(ui_Label16, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label16, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label16, 0);
    lv_obj_set_y(ui_Label16, 71);
    lv_obj_set_align(ui_Label16, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label16, "Return");
    lv_obj_set_style_text_font(ui_Label16, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button13 = lv_btn_create(ui_Screen4);
    lv_obj_set_width(ui_Button13, 72);
    lv_obj_set_height(ui_Button13, 27);
    lv_obj_set_x(ui_Button13, 2);
    lv_obj_set_y(ui_Button13, 97);
    lv_obj_set_align(ui_Button13, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_Button13, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button13, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_Button13, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_Button13, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button14 = lv_btn_create(ui_Screen4);
    lv_obj_set_width(ui_Button14, 72);
    lv_obj_set_height(ui_Button14, 36);
    lv_obj_set_x(ui_Button14, -66);
    lv_obj_set_y(ui_Button14, 78);
    lv_obj_set_align(ui_Button14, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_Button14, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button14, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_Button14, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_Button14, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button15 = lv_btn_create(ui_Screen4);
    lv_obj_set_width(ui_Button15, 27);
    lv_obj_set_height(ui_Button15, 152);
    lv_obj_set_x(ui_Button15, -44);
    lv_obj_set_y(ui_Button15, 27);
    lv_obj_set_align(ui_Button15, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_Button15, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button15, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_Button15, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_Button15, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button16 = lv_btn_create(ui_Screen4);
    lv_obj_set_width(ui_Button16, 26);
    lv_obj_set_height(ui_Button16, 147);
    lv_obj_set_x(ui_Button16, 41);
    lv_obj_set_y(ui_Button16, 27);
    lv_obj_set_align(ui_Button16, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_Button16, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button16, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_Button16, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_Button16, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button17 = lv_btn_create(ui_Screen4);
    lv_obj_set_width(ui_Button17, 66);
    lv_obj_set_height(ui_Button17, 33);
    lv_obj_set_x(ui_Button17, 64);
    lv_obj_set_y(ui_Button17, 75);
    lv_obj_set_align(ui_Button17, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_Button17, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button17, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_Button17, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_Button17, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button19 = lv_btn_create(ui_Screen4);
    lv_obj_set_width(ui_Button19, 57);
    lv_obj_set_height(ui_Button19, 50);
    lv_obj_set_x(ui_Button19, -2);
    lv_obj_set_y(ui_Button19, 33);
    lv_obj_set_align(ui_Button19, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_Button19, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button19, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_Button19, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_Button19, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_screen4ReturnBt, ui_event_screen4ReturnBt, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_lightArc, s4_arc_event_cb, LV_EVENT_ALL, NULL);

}
