esphome:
  name: 28-test
  friendly_name: 2.8_test

esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "0vvxdBQ8eKDCOsEC7zyy1zXvksjTEmxuyABfKXearho="

ota:
  password: "1e2c649bc50cce83058c6f64dc35cd9b"

wifi:
  id: wifi_1
  ssid: "yanfa_software"
  password: "yanfa-123456"

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Hmi-28 Fallback Hotspot"
    password: "UjyYsnN9rDTD"

captive_portal:
#设置背光引脚
# Define a PWM output on the ESP32
output:
  - platform: ledc
    pin: GPIO27
    inverted: False
    id: backlight_pwm

# Define a monochromatic, dimmable light for the backlight
#打开背光

light:
  - platform: monochromatic
    output: backlight_pwm
    name: "Display Backlight"
    id: back_light
    restore_mode: ALWAYS_ON
#设置字体    
font:
  - file: "gfonts://Roboto"
    id: font4
    size: 48
  - file: "gfonts://Roboto"
    id: font3
    size: 36
  - file: "gfonts://Roboto"
    id: font2
    size: 24
  - file: "gfonts://Roboto"
    id: font1
    size: 12


#设置I2C
i2c:
  sda: 22
  scl: 21

#sensor:
 # - platform: aht10 #dht12 #am2320 #
 #   temperature:
 #     name: "HMI-24 Temperature"
 #     id: temperature24
#    humidity:
#      name: "HMI-24 Humidity"
#      id: humidity24
#    update_interval: 10s
#设置tsl2561传感器，DHT22温湿度传感器
sensor:
  - platform: tsl2561
    name: "TSL2561 Ambient Light"
    id: TSL2561
    address: 0x29
    update_interval: 2s
  - platform: dht
    pin: 25
    temperature:
      name: "HMI-24 Temperature"
      id: temperature24
    humidity:
      id: humidity24
      name: "HMI-24 Humidity"
    update_interval: 5s
    model: DHT22

#设置SPI引脚
spi:
  clk_pin: 14
  mosi_pin: 13
  miso_pin: 12


#引入UI素材文件 
image:
  - file: "light.png"
    id: on_light
    resize: 50x50
    type: RGB24
  - file: "small_hum.png"
    id: small_hum
    resize: 50x75
    type: RGB24
  - file: "small_logo.png"
    id: small_logo
    resize: 250x52
    type: RGB24
  - file: "small_off.png"
    id: small_off
    resize: 50x75
    type: RGB24
  - file: "small_temp.png"
    id: small_temp
    resize: 50x75
    type: RGB24
  - file: "no_light.png"
    id: no_light
    resize: 50x50
    type: RGB24
#定义不同颜色
color:
  - id: my_red
    red: 100%
    green: 0%
    blue: 0%
  - id: my_white
    red: 100%
    green: 100%
    blue: 100%
  - id: my_green
    red: 0%
    green: 100%
    blue: 0%
  - id: my_blue
    red: 0%
    green: 0%
    blue: 100%
  - id: my_black
    red: 0%
    green: 0%
    blue: 0%
 #设置显示器并显示UI                
display:
  - platform: ili9xxx
    id: dp
    model: ili9341
    dc_pin: 2
    cs_pin: 15
    rotation: 90
    lambda: |-     
      it.fill(id(my_white));
      it.image(35, 0, id(small_logo));
      it.image(35, 150, id(on_light));
      it.image(155, 130, id(small_temp));
      it.image(255, 130, id(small_hum));
      it.printf(40, 210, id(font2), id(my_black), "%.1f", id(TSL2561).state);
      it.printf(160, 210, id(font2), id(my_black), "%.1f", id(temperature24).state);
      it.printf(260, 210, id(font2), id(my_black), "%.1f", id(humidity24).state);




# display:
#   - platform: ili9xxx
#     model: ili9341
#     dc_pin: 2
#     cs_pin: 15
#     rotation: 90
#     lambda: |-     
#       it.fill(id(my_color));
#       it.fill(id(my_color));
#       it.image(0, 0, id(my_image));
#       it.print(0, 0, id(font3), id(my_red), TextAlign::TOP_LEFT, "WillPower:");    
    